/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Wilayah {
  kode: string;
  nama: string | null;
}

export interface DB {
  wilayah: Wilayah;
}
